version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      target-branch: "nightly"
      schedule:
          interval: daily
    - package-ecosystem: npm
      directory: "/client"
      target-branch: "nightly"
      schedule:
          interval: daily
