name: Check build status
on: [push, pull_request]

jobs:
    build:
        name: Build test
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: yarn build:install
            - name: Check yarn.lock
              run: git diff --exit-code yarn.lock
            - name: Check yarn.lock (client)
              run: git diff --exit-code client/yarn.lock
            - name: Build
              run: yarn build:compile
